## Content Based Recomender System

In [1]:
import pandas as pd
import numpy as np

In [3]:
credit = pd.read_csv(r"..\archive\tmdb_5000_credits.csv")
credit

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [4]:
movies = pd.read_csv(r"../archive/tmdb_5000_movies.csv")
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [5]:
credit.shape, movies.shape

((4803, 4), (4803, 20))

In [6]:
final = movies.merge(credit, on='title')
final.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
final.shape

(4809, 23)

In [8]:
# Keeping important columns for recommendation
final = final[['movie_id','title','overview','genres','keywords','cast','crew']]
final.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [9]:
final.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
final.dropna(inplace=True)

In [11]:
final.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
final.duplicated().sum()

0

In [14]:
# Handeling The Genere Column
final.iloc[1]['genres']

'[{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]'

In [15]:
import ast # Converting The String To List

def convert_list(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
        
    return L

In [16]:
final['genres'] = final['genres'].apply(convert_list)

In [17]:
final.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [18]:
# Handeling The keywords Column
final.iloc[1]['keywords']

'[{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic island"}, {"id": 1319, "name": "east india trading company"}, {"id": 2038, "name": "love of one\'s life"}, {"id": 2052, "name": "traitor"}, {"id": 2580, "name": "shipwreck"}, {"id": 2660, "name": "strong woman"}, {"id": 3799, "name": "ship"}, {"id": 5740, "name": "alliance"}, {"id": 5941, "name": "calypso"}, {"id": 6155, "name": "afterlife"}, {"id": 6211, "name": "fighter"}, {"id": 12988, "name": "pirate"}, {"id": 157186, "name": "swashbuckler"}, {"id": 179430, "name": "aftercreditsstinger"}]'

In [19]:
final['keywords'] = final['keywords'].apply(convert_list)

In [20]:
final.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [21]:
# Handeling The Cast Column
final.iloc[0]['cast']

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [22]:
# Here I am Slecting Top 4 Cast
def convert_cast(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 4:
            L.append(i['name'])
        counter += 1
    return L

In [23]:
final['cast'] = final['cast'].apply(convert_cast)

In [24]:
final.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [25]:
# Handeling The Crew Column
final.iloc[0]['crew']

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [26]:
# Fetch Only Director
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [27]:
final['crew'] = final['crew'].apply(fetch_director)

In [28]:
final.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]

In [29]:
# Handeling The Overview Column
final.iloc[0]['overview']

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [30]:
final['overview'] = final['overview'].apply(lambda x:x.split())
final.sample(4)

,movie_id,title,overview,genres,keywords,cast,crew
4221,10758,Waitress,"[Jenna, is, a, pregnant,, unhappily, married, ...",[Comedy],"[waitress, unwillingly pregnant, woman director]","[Keri Russell, Nathan Fillion, Andy Griffith, ...",[Adrienne Shelly]
2929,1817,Phone Booth,"[A, slick, New, York, publicist, who, picks, u...","[Thriller, Drama]","[terrorist, phone booth, psychopath]","[Colin Farrell, Kiefer Sutherland, Forest Whit...",[Joel Schumacher]
3738,10947,High School Musical,"[Troy, (Zac, Efron),, the, popular, captain, o...","[Comedy, Drama, Family, Music, TV Movie]","[becoming an adult, musical, music, high schoo...","[Zac Efron, Vanessa Hudgens, Ashley Tisdale, L...",[Kenny Ortega]
944,66,Absolute Power,"[A, master, thief, coincidentally, is, robbing...","[Crime, Drama, Thriller]","[corruption, assassination, washington d.c., r...","[Clint Eastwood, Gene Hackman, Ed Harris, Scot...",[Clint Eastwood]

In [31]:
# Now Removing space like that 
'Anna Kendrick'
'AnnaKendrick'

def remove_space_between(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [32]:
final['cast'] = final['cast'].apply(remove_space_between)
final['crew'] = final['crew'].apply(remove_space_between)
final['genres'] = final['genres'].apply(remove_space_between)
final['keywords'] = final['keywords'].apply(remove_space_between)

In [33]:
final.sample(4)

,movie_id,title,overview,genres,keywords,cast,crew
1353,10219,Snow Falling on Cedars,"[A, Japanese-American, fisherman, may, have, k...","[Drama, Romance]","[journalist, japanese, wife, fisherman, war, b...","[EthanHawke, YoukiKudoh, ReeveCarney, AnneSuzuki]",[ScottHicks]
2961,1590,Copying Beethoven,"[A, fictionalised, exploration, of, Beethoven'...",[Drama],"[beethoven, womandirector]","[EdHarris, DianeKruger, MatthewGoode, Phyllida...",[AgnieszkaHolland]
3015,9794,Employee of the Month,"[When, he, hears, that, the, new, female, empl...","[Comedy, Romance]","[salesclerk, midlifecrisis, prenzlauerberg, vu...","[DaneCook, JessicaSimpson, DaxShepard, AndyDick]",[GregCoolidge]
505,8698,The League of Extraordinary Gentlemen,"[To, prevent, a, world, war, from, breaking, o...","[Fantasy, Action, Thriller, ScienceFiction]","[savingtheworld, vampire, bite, men, invisible...","[SeanConnery, PetaWilson, ShaneWest, StuartTow...",[StephenNorrington]

In [34]:
# Concatenate
final['tags'] = final['overview'] + final['keywords'] + final['genres'] + final['cast'] + final['crew']
final.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [35]:
final.iloc[0]['tags']

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'StephenLang',
 'JamesCameron']

In [36]:
new_df = final[['movie_id', 'title', 'tags']]
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [37]:
# Connvert List To Str
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df.head()

D:\DVC & MLFlow Project\Movie-Recommender-System-Using-Machine-Learning\env\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [39]:
new_df.iloc[0]['tags']

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver StephenLang JamesCameron'

In [40]:
# Connvert Lower Case
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())
new_df.head()

D:\DVC & MLFlow Project\Movie-Recommender-System-Using-Machine-Learning\env\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [41]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [43]:
import nltk
from nltk.stem import PorterStemmer

In [44]:
ps = PorterStemmer()

def stems(text):
    T = []
    for i in text.split():
        T.append(ps.stem(i))
        
    return " ".join(T)

In [45]:
new_df['tags'] = new_df['tags'].apply(stems)

D:\DVC & MLFlow Project\Movie-Recommender-System-Using-Machine-Learning\env\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [46]:
new_df.iloc[0]['tags']

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav stephenlang jamescameron'

In [47]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [48]:
vector = cv.fit_transform(new_df['tags']).toarray()
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [50]:
vector.shape, len(cv.get_feature_names_out())

((4806, 5000), 5000)

In [51]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)
similarity

array([[1.        , 0.08226127, 0.0860309 , ..., 0.04543109, 0.        ,
        0.        ],
       [0.08226127, 1.        , 0.05976143, ..., 0.02366905, 0.        ,
        0.02577696],
       [0.0860309 , 0.05976143, 1.        , ..., 0.02475369, 0.        ,
        0.        ],
       ...,
       [0.04543109, 0.02366905, 0.02475369, ..., 1.        , 0.04174829,
        0.04270814],
       [0.        , 0.        , 0.        , ..., 0.04174829, 1.        ,
        0.09093258],
       [0.        , 0.02577696, 0.        , ..., 0.04270814, 0.09093258,
        1.        ]])

In [52]:
similarity.shape

(4806, 4806)

In [54]:
index=new_df[new_df['title'] == 'The Lego Movie'].index[0]
index

744

In [60]:
distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])
distance

[(744, 0.9999999999999998),
 (934, 0.2817879814705388),
 (368, 0.27456258919345766),
 (503, 0.26916687204956063),
 (179, 0.2631174057921088),
 (234, 0.2597621667330656),
 (742, 0.2549249642552304),
 (506, 0.2508726030021272),
 (73, 0.24535824603285925),
 (2533, 0.24535824603285925),
 (1280, 0.24019223070763074),
 (558, 0.23782574707724705),
 (410, 0.23388213848187447),
 (546, 0.23076923076923078),
 (359, 0.22645540682891915),
 (42, 0.22413272587221034),
 (254, 0.22413272587221034),
 (1701, 0.22413272587221034),
 (154, 0.22237479499833035),
 (131, 0.2198260025574647),
 (2686, 0.2170607855311148),
 (40, 0.21439736214109112),
 (1137, 0.21134098610290408),
 (1989, 0.2096569673443837),
 (343, 0.2094723288520775),
 (374, 0.2065829169621999),
 (294, 0.2048366225996757),
 (810, 0.20483662259967567),
 (3860, 0.20483662259967567),
 (459, 0.2044652050273827),
 (1194, 0.2044652050273827),
 (4290, 0.2044652050273827),
 (221, 0.20241022618818408),
 (569, 0.20241022618818408),
 (837, 0.20180183819889372),
 (942, 0.2002453486917181),
 (325, 0.20016019225635895),
 (604, 0.20016019225635895),
 (1381, 0.20016019225635895),
 (121, 0.1988980632395388),
 (1065, 0.1988980632395388),
 (1688, 0.19889806323953876),
 (3407, 0.19814848097530427),
 (3907, 0.19814848097530424),
 (429, 0.19611613513818404),
 (2331, 0.19611613513818404),
 (4055, 0.19611613513818402),
 (130, 0.196116135138184),
 (1682, 0.196116135138184),
 (896, 0.194601702164208),
 (194, 0.19230769230769232),
 (2562, 0.19230769230769232),
 (268, 0.19088542889273336),
 (90, 0.1887128390240993),
 (117, 0.1887128390240993),
 (1432, 0.18681617943926832),
 (34, 0.1853123291652753),
 (980, 0.1853123291652753),
 (2120, 0.1853123291652753),
 (1104, 0.18490006540840975),
 (187, 0.18376916754950667),
 (1290, 0.18376916754950667),
 (348, 0.18208926018230742),
 (533, 0.18208926018230742),
 (144, 0.18156825980064073),
 (4542, 0.179968508266339),
 (3285, 0.17944458136637376),
 (781, 0.17902871850985821),
 (514, 0.1773937187967248),
 (195, 0.17611748841908675),
 (1249, 0.17611748841908675),
 (460, 0.17349447958987207),
 (566, 0.1716388703071869),
 (435, 0.17118419700436519),
 (1904, 0.17118419700436519),
 (142, 0.17069718549972973),
 (1692, 0.16984155512168939),
 (1032, 0.1681681984990781),
 (418, 0.16724840200141816),
 (778, 0.16641005886756874),
 (3008, 0.165748386032949),
 (152, 0.16574838603294897),
 (3428, 0.16343011261515336),
 (241, 0.16343011261515333),
 (2659, 0.16343011261515333),
 (66, 0.16317848796612638),
 (124, 0.16317848796612638),
 (2278, 0.16317848796612638),
 (2856, 0.16317848796612638),
 (2470, 0.16163173753210963),
 (2596, 0.1616317375321096),
 (328, 0.16120647005479027),
 (899, 0.16120647005479027),
 (2683, 0.16120647005479027),
 (393, 0.16120647005479025),
 (109, 0.16012815380508716),
 (935, 0.16012815380508716),
 (1077, 0.16012815380508716),
 (1727, 0.16012815380508716),
 (2101, 0.16012815380508716),
 (3629, 0.16012815380508716),
 (814, 0.15907119074394446),
 (509, 0.15866576560438356),
 (2133, 0.15866576560438356),
 (458, 0.15724272550828777),
 (3185, 0.15724272550828777),
 (390, 0.15701857325533192),
 (177, 0.15689290811054724),
 (1662, 0.15689290811054724),
 (2268, 0.15689290811054724),
 (3584, 0.15689290811054724),
 (1089, 0.15544045708951462),
 (138, 0.15504341823651058),
 (196, 0.15504341823651058),
 (874, 0.15504341823651058),
 (572, 0.15450786078738143),
 (791, 0.15384615384615385),
 (1201, 0.15384615384615385),
 (1365, 0.15384615384615385),
 (1547, 0.15319287635644963),
 (563, 0.15314097295792223),
 (1740, 0.15314097295792223),
 (1862, 0.15191090506254998),
 (3049, 0.15191090506254998),
 (15, 0.15191090506254995),
 (184, 0.15130688316720062),
 (631, 0.15130688316720062),
 (754, 0.15130688316720062),
 (202, 0.15097027121927944),
 (3133, 0.15097027121927944),
 (255, 0.1495371511386448),
 (1369, 0.1495371511386448),
 (2300, 0.1495371511386448),
 (106, 0.1494406444160154),
 (84, 0.14944064441601537),
 (309, 0.14824986333222023),
 (452, 0.14824986333222023),
 (1217, 0.14824986333222023),
 (1976, 0.14824986333222023),
 (2253, 0.14782809899727067),
 (812, 0.14708710135363803),
 (2043, 0.14708710135363803),
 (178, 0.14617633655117154),
 (431, 0.14617633655117154),
 (1593, 0.145951276623156),
 (94, 0.14567140814584595),
 (1658, 0.14567140814584595),
 (2546, 0.14567140814584595),
 (1361, 0.14484136487558028),
 (1500, 0.14457873299156007),
 (1831, 0.14457873299156007),
 (1938, 0.14457873299156007),
 (88, 0.14322297480788657),
 (358, 0.14322297480788657),
 (1047, 0.14322297480788657),
 (1364, 0.14322297480788657),
 (1626, 0.14322297480788657),
 (2075, 0.14322297480788657),
 (2145, 0.14322297480788657),
 (175, 0.14303239192265577),
 (399, 0.14303239192265577),
 (543, 0.14303239192265577),
 (1664, 0.14269544824634822),
 (3063, 0.14269544824634822),
 (4010, 0.14269544824634822),
 (86, 0.14153462926807447),
 (525, 0.14153462926807447),
 (2903, 0.14153462926807447),
 (269, 0.1408939907352694),
 (292, 0.1408939907352694),
 (1586, 0.1408939907352694),
 (160, 0.14084763640246842),
 (243, 0.14008295367013146),
 (1043, 0.14008295367013146),
 (3452, 0.14008295367013146),
 (1502, 0.13867504905630731),
 (1956, 0.13867504905630731),
 (23, 0.1386750490563073),
 (141, 0.1386750490563073),
 (289, 0.1386750490563073),
 (385, 0.1386750490563073),
 (413, 0.1386750490563073),
 (1334, 0.1386750490563073),
 (1568, 0.1386750490563073),
 (2330, 0.1386750490563073),
 (1081, 0.13730875909527243),
 (391, 0.13678822577626598),
 (441, 0.1365577483997838),
 (725, 0.1365577483997838),
 (931, 0.1365577483997838),
 (2196, 0.1365577483997838),
 (2402, 0.1365577483997838),
 (2576, 0.1365577483997838),
 (2816, 0.1365577483997838),
 (704, 0.1359820733051053),
 (734, 0.1359820733051053),
 (848, 0.13587324409735146),
 (1209, 0.13497638119975425),
 (1770, 0.13497638119975425),
 (2445, 0.13497638119975425),
 (3918, 0.13497638119975425),
 (181, 0.13469311461009137),
 (420, 0.13469311461009137),
 (1906, 0.13469311461009137),
 (777, 0.13469311461009134),
 (428, 0.13409704688030227),
 (3617, 0.13409704688030227),
 (39, 0.13259870882635919),
 (539, 0.13259870882635919),
 (859, 0.13259870882635919),
 (1585, 0.13259870882635919),
 (1983, 0.13259870882635919),
 (2128, 0.13259870882635919),
 (2817, 0.13259870882635919),
 (3470, 0.13259870882635919),
 (858, 0.1315587028960544),
 (1582, 0.1315587028960544),
 (2369, 0.1315587028960544),
 (3155, 0.1315587028960544),
 (4131, 0.1315587028960544),
 (4443, 0.1315587028960544),
 (565, 0.1310356045902398),
 (692, 0.1310356045902398),
 (1767, 0.1310356045902398),
 (67, 0.13074409009212268),
 (306, 0.13074409009212268),
 (937, 0.13074409009212268),
 (3498, 0.13074409009212268),
 (4409, 0.13074409009212268),
 (172, 0.1283881477532739),
 (797, 0.1283881477532739),
 (1240, 0.1283881477532739),
 (1892, 0.1283881477532739),
 (3096, 0.1283881477532739),
 (4185, 0.1283881477532739),
 (1305, 0.12766073029704134),
 (258, 0.12763068894345514),
 (37, 0.12725695259515557),
 (126, 0.12725695259515557),
 (1325, 0.12725695259515557),
 (1388, 0.12725695259515557),
 (555, 0.12691660175143163),
 (305, 0.1265924208854583),
 (55, 0.12615514005935402),
 (485, 0.12561485860426555),
 (1993, 0.12561485860426555),
 (3551, 0.12561485860426555),
 (92, 0.12555049023795636),
 (3781, 0.12543630150106364),
 (336, 0.1254363015010636),
 (748, 0.1254363015010636),
 (1166, 0.1254363015010636),
 (1525, 0.1254363015010636),
 (1737, 0.1254363015010636),
 (3678, 0.1254363015010636),
 (836, 0.12453387034667948),
 (14, 0.12403473458920847),
 (324, 0.12403473458920847),
 (2276, 0.12403473458920847),
 (2544, 0.12403473458920847),
 (3804, 0.12403473458920847),
 (63, 0.1235415527768502),
 (2191, 0.1235415527768502),
 (494, 0.12267912301642962),
 (1860, 0.12267912301642962),
 (3055, 0.12267912301642962),
 (3479, 0.12267912301642962),
 (3877, 0.12267912301642962),
 (375, 0.12257258446136503),
 (78, 0.12251277836633778),
 (235, 0.12251277836633778),
 (349, 0.12251277836633778),
 (492, 0.12251277836633778),
 (2357, 0.12251277836633778),
 (2449, 0.12251277836633778),
 (2481, 0.12251277836633778),
 (2828, 0.12251277836633778),
 (488, 0.12136700910941023),
 (689, 0.12104550653376049),
 (1260, 0.12104550653376049),
 (949, 0.1207011373963169),
 (61, 0.12009611535381537),
 (148, 0.12009611535381537),
 (263, 0.12009611535381537),
 (1884, 0.12009611535381537),
 (3129, 0.12009611535381537),
 (1600, 0.11979699629569004),
 (111, 0.11962972091091584),
 (210, 0.11962972091091584),
 (545, 0.11962972091091584),
 (1070, 0.11962972091091584),
 (2750, 0.11962972091091584),
 (3783, 0.11962972091091584),
 (103, 0.11891287353862354),
 (299, 0.11891287353862354),
 (136, 0.11826247919781653),
 (1048, 0.11826247919781653),
 (1299, 0.11826247919781653),
 (1972, 0.11826247919781653),
 (2055, 0.11826247919781653),
 (2237, 0.11826247919781653),
 (2988, 0.11826247919781653),
 (4315, 0.11826247919781653),
 (4466, 0.11804804116247142),
 (146, 0.11766968108291043),
 (237, 0.11766968108291043),
 (1343, 0.11766968108291043),
 (1852, 0.11766968108291043),
 (2309, 0.11766968108291043),
 (1426, 0.11720180773462385),
 (9, 0.11694106924093724),
 (784, 0.11694106924093724),
 (2215, 0.11694106924093724),
 (318, 0.11637351602893195),
 (639, 0.11566298639324805),
 (870, 0.11566298639324805),
 (161, 0.11538461538461539),
 (707, 0.11538461538461539),
 (766, 0.11538461538461539),
 (1724, 0.11538461538461539),
 (1833, 0.11538461538461539),
 (2463, 0.11538461538461539),
 (2515, 0.11538461538461539),
 (3060, 0.11538461538461539),
 (3143, 0.11538461538461539),
 (4436, 0.11538461538461539),
 (4314, 0.11476828720122217),
 (728, 0.11442591353812462),
 (1145, 0.11442591353812462),
 (2344, 0.11442591353812462),
 (2831, 0.11442591353812462),
 (302, 0.11322770341445959),
 (364, 0.11322770341445959),
 (495, 0.11322770341445959),
 (636, 0.11322770341445959),
 (686, 0.11322770341445959),
 (903, 0.11322770341445959),
 (1158, 0.11322770341445959),
 (1276, 0.11322770341445959),
 (1686, 0.11322770341445959),
 (2529, 0.11322770341445959),
 (2531, 0.11322770341445959),
 (3888, 0.11322770341445959),
 (4281, 0.11322770341445959),
 (4405, 0.11322770341445959),
 (4757, 0.11322770341445959),
 (578, 0.11322770341445956),
 (2005, 0.11322770341445956),
 (743, 0.11206636293610517),
 (3925, 0.11206636293610517),
 (2182, 0.11174753906691855),
 (54, 0.11118739749916517),
 (276, 0.11118739749916517),
 (504, 0.11118739749916517),
 (769, 0.11118739749916517),
 (1442, 0.11118739749916517),
 (1606, 0.11118739749916517),
 (1902, 0.11118739749916517),
 (1973, 0.11118739749916517),
 (2127, 0.11118739749916517),
 (2745, 0.11118739749916517),
 (2776, 0.11094003924504584),
 (3992, 0.11094003924504584),
 (114, 0.10984700727621795),
 (3540, 0.10984700727621795),
 (1058, 0.10925355610938446),
 (1408, 0.10925355610938446),
 (1434, 0.10925355610938446),
 (1584, 0.10925355610938446),
 (1709, 0.10925355610938446),
 (2251, 0.10925355610938446),
 (2348, 0.10925355610938446),
 (2684, 0.10925355610938446),
 (3999, 0.10925355610938446),
 (4091, 0.10925355610938446),
 (464, 0.10878565864408425),
 (1075, 0.10878565864408425),
 (1377, 0.10878565864408425),
 (2025, 0.10878565864408425),
 (2092, 0.10878565864408425),
 (4014, 0.10878565864408425),
 (3212, 0.1085303927655574),
 (981, 0.10775449168807308),
 (1752, 0.10775449168807308),
 (1783, 0.10775449168807308),
 (8, 0.10741723110591492),
 (2810, 0.10741723110591492),
 (2920, 0.10699012312772824),
 (3570, 0.10675210253672476),
 (143, 0.10577717706958903),
 (2109, 0.10577717706958903),
 (1477, 0.10573873360945339),
 (1309, 0.10573873360945338),
 (167, 0.10567049305145204),
 (554, 0.10567049305145204),
 (926, 0.10567049305145204),
 (989, 0.10567049305145204),
 (1760, 0.10567049305145204),
 (2122, 0.10567049305145204),
 (2146, 0.10567049305145204),
 (2840, 0.10567049305145204),
 (2927, 0.10567049305145204),
 (518, 0.10482848367219184),
 (618, 0.10482848367219184),
 (698, 0.10482848367219184),
 (1409, 0.10482848367219184),
 (1459, 0.10482848367219184),
 (2618, 0.10482848367219184),
 (2749, 0.10482848367219184),
 (3017, 0.10482848367219184),
 (3130, 0.10482848367219184),
 (3275, 0.10482848367219184),
 (3390, 0.10482848367219184),
 (3529, 0.10482848367219184),
 (3726, 0.10482848367219184),
 (3966, 0.10482848367219184),
 (4516, 0.10482848367219184),
 (77, 0.10400628679223047),
 (133, 0.10400628679223047),
 (198, 0.10400628679223047),
 (960, 0.10400628679223047),
 (1556, 0.10400628679223047),
 (3005, 0.10400628679223047),
 (3053, 0.10400628679223047),
 (4121, 0.10400628679223047),
 (2354, 0.10390486669322624),
 (1124, 0.10300524052492095),
 (1155, 0.10300524052492095),
 (2838, 0.10300524052492094),
 (917, 0.10241831129983785),
 (1695, 0.10241831129983785),
 (1750, 0.10241831129983785),
 (3071, 0.10241831129983785),
 (4775, 0.10241831129983785),
 (32, 0.10212858423763307),
 (612, 0.10212858423763307),
 (3522, 0.10212858423763307),
 (1863, 0.10148125307008302),
 (443, 0.10127393670836665),
 (3218, 0.10127393670836665),
 (3941, 0.10127393670836665),
 (4606, 0.10127393670836665),
 (118, 0.10113917425784186),
 (50, 0.10090091909944687),
 (232, 0.10090091909944687),
 (1982, 0.10090091909944687),
 (2304, 0.10090091909944687),
 (2826, 0.10090091909944687),
 (3257, 0.10090091909944687),
 (48, 0.10044039219036509),
 (403, 0.10044039219036509),
 (2439, 0.10044039219036509),
 (406, 0.09962709627734359),
 (661, 0.09962709627734359),
 (2978, 0.09962709627734359),
 (4729, 0.09962709627734359),
 (46, 0.0994490316197694),
 (265, 0.0994490316197694),
 (288, 0.0994490316197694),
 (313, 0.0994490316197694),
 (341, 0.0994490316197694),
 (352, 0.0994490316197694),
 (1150, 0.0994490316197694),
 (1527, 0.0994490316197694),
 (2169, 0.0994490316197694),
 (2661, 0.0994490316197694),
 (2768, 0.0994490316197694),
 (3137, 0.0994490316197694),
 (3410, 0.0994490316197694),
 (3581, 0.0994490316197694),
 (4110, 0.0994490316197694),
 (4175, 0.0994490316197694),
 (3182, 0.09944903161976938),
 (501, 0.09883324222148016),
 (2106, 0.09883324222148016),
 (381, 0.09805806756909202),
 (489, 0.09805806756909202),
 (1444, 0.09805806756909202),
 (1599, 0.09805806756909202),
 (1855, 0.09805806756909202),
 (2332, 0.09805806756909202),
 (2353, 0.09805806756909202),
 (2534, 0.09805806756909202),
 (2674, 0.09805806756909202),
 (3527, 0.09805806756909202),
 (227, 0.09805806756909201),
 (327, 0.09805806756909201),
 (332, 0.09805806756909201),
 (472, 0.09805806756909201),
 (807, 0.09805806756909201),
 (843, 0.09805806756909201),
 (901, 0.09805806756909201),
 (1237, 0.09805806756909201),
 (1827, 0.09805806756909201),
 (1945, 0.09805806756909201),
 (2172, 0.09805806756909201),
 (2452, 0.09805806756909201),
 (3251, 0.09805806756909201),
 (6, 0.097300851082104),
 (245, 0.09672388203287416),
 (427, 0.09672388203287416),
 (646, 0.09672388203287416),
 (1739, 0.09672388203287416),
 (1808, 0.09672388203287416),
 (2767, 0.09672388203287416),
 (3677, 0.09672388203287416),
 (3847, 0.09672388203287416),
 (673, 0.09656090991705352),
 (1828, 0.09656090991705352),
 (2226, 0.09656090991705352),
 (1503, 0.09583759703655205),
 (16, 0.09544271444636668),
 (1080, 0.09544271444636668),
 (1597, 0.09544271444636668),
 (2164, 0.09544271444636668),
 (3222, 0.09544271444636668),
 (4078, 0.09544271444636668),
 (4260, 0.09544271444636668),
 (897, 0.09513029883089882),
 (966, 0.09513029883089882),
 (1986, 0.09513029883089882),
 (2040, 0.09513029883089882),
 (2165, 0.09513029883089882),
 (2339, 0.09513029883089882),
 (2725, 0.09513029883089882),
 (3281, 0.09513029883089882),
 (4000, 0.09513029883089882),
 (4040, 0.09513029883089882),
 (4400, 0.09513029883089882),
 (4407, 0.09513029883089882),
 (4747, 0.09513029883089882),
 (47, 0.09443843292997713),
 (2362, 0.09443843292997713),
 (329, 0.09421114395319916),
 (1071, 0.09421114395319916),
 (1416, 0.09421114395319916),
 (3152, 0.09421114395319916),
 (3249, 0.09421114395319916),
 (65, 0.09376144618769909),
 (1555, 0.09309881282314555),
 (1924, 0.09309881282314555),
 (411, 0.09302605094190636),
 (2177, 0.09302605094190636),
 (2851, 0.09302605094190636),
 (2973, 0.09302605094190636),
 (3091, 0.09302605094190636),
 (3894, 0.09302605094190634),
 (1045, 0.09245003270420488),
 (1300, 0.09245003270420488),
 (1613, 0.09245003270420488),
 (1868, 0.09245003270420488),
 (3282, 0.09245003270420488),
 (3350, 0.09245003270420488),
 (4056, 0.09245003270420488),
 (4635, 0.09245003270420488),
 (10, 0.09188458377475334),
 (70, 0.09188458377475334),
 (369, 0.09188458377475334),
 (416, 0.09188458377475334),
 (430, 0.09188458377475334),
 (436, 0.09188458377475334),
 (605, 0.09188458377475334),
 (835, 0.09188458377475334),
 (1123, 0.09188458377475334),
 (1296, 0.09188458377475334),
 (1511, 0.09188458377475334),
 (3357, 0.09188458377475334),
 (238, 0.09119215051751065),
 (551, 0.09119215051751065),
 (98, 0.09078412990032037),
 (168, 0.09078412990032037),
 (1009, 0.09078412990032037),
 (1266, 0.09078412990032037),
 (1753, 0.09078412990032037),
 (1888, 0.09078412990032037),
 (3366, 0.09078412990032037),
 (4264, 0.09078412990032037),
 (1371, 0.09058216273156765),
 (189, 0.0899842541331695),
 (205, 0.0899842541331695),
 (465, 0.0899842541331695),
 (627, 0.0899842541331695),
 (699, 0.0899842541331695),
 (906, 0.0899842541331695),
 (1521, 0.0899842541331695),
 (1990, 0.0899842541331695),
 (2518, 0.0899842541331695),
 (3579, 0.0899842541331695),
 (3625, 0.0899842541331695),
 (3694, 0.0899842541331695),
 (3711, 0.0899842541331695),
 (3721, 0.0899842541331695),
 (4129, 0.08988968316207743),
 (2436, 0.08972229068318688),
 (3935, 0.08972229068318688),
 (4644, 0.08972229068318688),
 (1487, 0.0888231183368655),
 (211, 0.0886968593983624),
 (340, 0.0886968593983624),
 (594, 0.0886968593983624),
 (898, 0.0886968593983624),
 (1623, 0.0886968593983624),
 (1885, 0.0886968593983624),
 (2269, 0.0886968593983624),
 (2352, 0.0886968593983624),
 (7, 0.08770580193070293),
 (71, 0.08770580193070293),
 (191, 0.08770580193070293),
 (350, 0.08770580193070293),
 (522, 0.08770580193070293),
 (614, 0.08770580193070293),
 (653, 0.08770580193070293),
 (833, 0.08770580193070293),
 (1308, 0.08770580193070293),
 (1367, 0.08770580193070293),
 (1689, 0.08770580193070293),
 (1696, 0.08770580193070293),
 (1841, 0.08770580193070293),
 (1925, 0.08770580193070293),
 (2118, 0.08770580193070293),
 (2183, 0.08770580193070293),
 (2212, 0.08770580193070293),
 (2317, 0.08770580193070293),
 (2694, 0.08770580193070293),
 (2742, 0.08770580193070293),
 (3069, 0.08770580193070293),
 (3219, 0.08770580193070293),
 (3702, 0.08770580193070293),
 (3716, 0.08770580193070293),
 (20, 0.08735706972682653),
 (89, 0.08701246455819893),
 (2998, 0.08701246455819893),
 (683, 0.08674723979493604),
 (816, 0.08674723979493604),
 (888, 0.08674723979493604),
 (1056, 0.08674723979493604),
 (2852, 0.08674723979493604),
 (3206, 0.08674723979493604),
 (4063, 0.08674723979493604),
 (339, 0.08581943515359347),
 (347, 0.08581943515359347),
 (481, 0.08581943515359347),
 (831, 0.08581943515359347),
 (1340, 0.08581943515359347),
 (2949, 0.08581943515359347),
 (3039, 0.08581943515359347),
 (3415, 0.08581943515359347),
 (3611, 0.08581943515359347),
 (233, 0.08559209850218259),
 (1000, 0.08559209850218259),
 (1174, 0.08559209850218259),
 (1394, 0.08559209850218259),
 (1575, 0.08559209850218259),
 (1782, 0.08559209850218259),
 (2089, 0.08559209850218259),
 (2094, 0.08559209850218259),
 (2313, 0.08559209850218259),
 (2381, 0.08559209850218259),
 (2416, 0.08559209850218259),
 (2510, 0.08559209850218259),
 (2763, 0.08559209850218259),
 (2809, 0.08559209850218259),
 (3217, 0.08559209850218259),
 (3771, 0.08559209850218259),
 (4020, 0.08559209850218259),
 (4157, 0.08559209850218259),
 (4444, 0.08559209850218259),
 (4638, 0.08559209850218259),
 (4582, 0.08508712596230342),
 (95, 0.08492077756084469),
 (933, 0.08492077756084469),
 (1168, 0.08492077756084469),
 (1273, 0.08492077756084469),
 (2103, 0.08492077756084469),
 (2358, 0.08492077756084469),
 (120, 0.08404977220207888),
 (225, 0.08404977220207888),
 (231, 0.08404977220207888),
 (377, 0.08404977220207888),
 (788, 0.08404977220207888),
 (1457, 0.08404977220207888),

In [61]:
for i in distance[1:6]:
    print(new_df.iloc[i[0]].title)

Curious George
Percy Jackson: Sea of Monsters
The Adventures of Rocky & Bullwinkle
Penguins of Madagascar
The Croods

In [62]:
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])
    for i in distance[1:6]:
        print(new_df.iloc[i[0]].title)

In [63]:
recommend('Spider-Man 2')

Spider-Man 3
Spider-Man
The Amazing Spider-Man
Iron Man 2
Superman

In [65]:
import pickle

pickle.dump(new_df,open('../artifacts/movie_list.pkl','wb'))
pickle.dump(similarity,open('../artifacts/similarity.pkl','wb'))